In [1]:
import gc
import os
import sys

import numpy as np
import optuna
import pandas as pd
import torch

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
device.type

'cuda'

In [3]:
%load_ext autoreload
%autoreload 2

from drGAT import drGAT

In [4]:
train_data = pd.read_csv("../CTRP_data/train.csv")
val_data = pd.read_csv("../CTRP_data/val.csv")
test_data = pd.read_csv("../CTRP_data/test.csv")

In [5]:
train_data.head()

,DRUG_NAME,CELL_LINE_NAME
0,BRD-K27986637,RERFLCAI
1,BRD-K09344309,NCIH1666
2,quizartinib,OVTOKO
3,BRD-K99584050,SNU878
4,ML210,YD15


In [6]:
idxs = np.load("../CTRP_data/idxs.npy", allow_pickle=True)
converter = {idxs[1, i]: int(idxs[0, i]) for i in range(idxs.shape[1])}

In [7]:
edge_index = np.load("../CTRP_data/edge_idxs.npy")
edge_attr = np.load("../CTRP_data/edge_attr.npy")

In [8]:
def get_idx(X):
    X["Drug"] = [converter[(i)] for i in X["DRUG_NAME"]]
    X["Cell"] = [converter[(i)] for i in X["CELL_LINE_NAME"]]
    return X

In [9]:
train_data = get_idx(train_data)
val_data = get_idx(val_data)
test_data = get_idx(test_data)

In [10]:
edge_index = torch.tensor(edge_index).int()
edge_index = edge_index.type(torch.int64)

In [11]:
edge_attr = torch.tensor(edge_attr).float()

In [12]:
train_drug = train_data["Drug"].values
train_cell = train_data["Cell"].values
val_drug = val_data["Drug"].values
val_cell = val_data["Cell"].values

In [13]:
train_labels = np.load("../CTRP_data/train_labels.npy")
val_labels = np.load("../CTRP_data/val_labels.npy")

train_labels = torch.tensor(train_labels).float()
val_labels = torch.tensor(val_labels).float()

## Get feature matrix

In [14]:
drug = pd.read_csv("../CTRP_data/drug_sim.csv", index_col=0)
cell = pd.read_csv("../CTRP_data/cell_sim.csv", index_col=0)
gene = pd.read_csv("../CTRP_data/gene_sim.csv", index_col=0)

In [15]:
drug = torch.tensor(drug.values).float()
cell = torch.tensor(cell.values).float()
gene = torch.tensor(gene.values).float()

# Create the dataset

In [16]:
data = [
    drug,
    cell,
    gene,
    edge_index,
    edge_attr,
    train_drug,
    train_cell,
    val_drug,
    val_cell,
    train_labels,
    val_labels,
]

In [17]:
params = {
    "dropout1": 0.1,
    "dropout2": 0.1,
    "n_drug": drug.shape[0],
    "n_cell": cell.shape[0],
    "n_gene": gene.shape[0],
    "hidden1": 256,
    "hidden2": 32,
    "hidden3": 128,
    "epochs": 3,
    "lr": 0.001,
    "heads": 2,
}

In [21]:
def objective(trial):
    params = {
        "n_drug": drug.shape[0],
        "n_cell": cell.shape[0],
        "n_gene": gene.shape[0],
        "dropout1": trial.suggest_categorical("dropout1", [0.1, 0.2, 0.3, 0.4, 0.5]),
        "dropout2": trial.suggest_categorical("dropout2", [0.1, 0.2, 0.3, 0.4, 0.5]),
        "hidden1": trial.suggest_categorical(
            "hidden1",
            [256, 512, 1028],
        ),
        "hidden2": trial.suggest_categorical(
            "hidden2",
            [
                128,
                256,
                512,
            ],
        ),
        "hidden3": trial.suggest_categorical(
            "hidden3",
            [
                64,
                128,
                256,
            ],
        ),
        "epochs": trial.suggest_int("epochs", 10, 200, step=50),
        "heads": trial.suggest_categorical("heads", [1, 2, 3]),
        "activation": trial.suggest_categorical(
            "activation", ["relu", "gelu", "swish"]
        ),
        "optimizer": trial.suggest_categorical("optimizer", ["Adam", "AdamW", "SGD"]),
        "lr": trial.suggest_float("lr", 1e-5, 1e-2, log=True),
        "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
        "scheduler": trial.suggest_categorical(
            "scheduler", [None, "Cosine", "Step", "Plateau"]
        ),
        "gnn_layer": trial.suggest_categorical(
            "gnn_layer", ["GAT", "GATv2", "Transformer"]
        ),
    }

    # スケジューラ関連パラメータの条件付き追加
    if params["scheduler"] == "Cosine":
        params["T_max"] = trial.suggest_int("T_max", 20, 50)
    elif params["scheduler"] == "Step":
        params["scheduler_gamma"] = trial.suggest_float("gamma_step", 0.1, 0.95)
        params["step_size"] = trial.suggest_int("step_size", 10, 30)
    elif params["scheduler"] == "Plateau":
        params["patience"] = trial.suggest_int("patience_plateau", 3, 10)
        params["threshold"] = trial.suggest_float(
            "thresh_plateau", 1e-4, 1e-2, log=True
        )

    if params["hidden1"] < params["hidden2"] or params["hidden2"] < params["hidden3"]:
        raise optuna.TrialPruned("Invalid layer size configuration")

    if params["optimizer"] in ["Adam", "AdamW"]:
        params["amsgrad"] = trial.suggest_categorical("amsgrad", [True, False])

    if params["optimizer"] == "SGD":
        params["momentum"] = trial.suggest_float("momentum", 0.8, 0.95)
        params["nesterov"] = trial.suggest_categorical("nesterov", [True, False])

    # 隠れ層サイズとバッチサイズの関係を制約
    if (params["hidden1"] > 512) and (params["hidden2"] > 256):
        raise optuna.TrialPruned("Memory intensive configuration")

    try:
        _, _, _, best_metrics, early_stopping_epoch = drGAT.train(
            data, params=params, device=device, verbose=False
        )

        early_stop_threshold = trial.suggest_float("early_stop_threshold", 0.3, 0.7)
        if (
            early_stopping_epoch is not None
            and early_stopping_epoch < params["epochs"] * early_stop_threshold
        ):
            raise optuna.TrialPruned("Early stopping occurred too early")

        trial.set_user_attr("early_stopping_epoch", early_stopping_epoch)
        return best_metrics

    except RuntimeError as e:
        if "CUDA out of memory" in str(e):
            print("CUDA out of memory")
            trial.set_user_attr("status", "CUDA OOM")

            torch.cuda.empty_cache()
            gc.collect()

            return [float("-inf")] * 4
        else:
            raise e

In [32]:
name = "CTRP"
study = optuna.create_study(
    directions=["maximize"] * 4,
    sampler=optuna.samplers.TPESampler(),
    pruner=optuna.pruners.HyperbandPruner(),
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
study.optimize(objective, n_trials=100)

[I 2025-03-20 12:39:58,769] Using an existing study with name 'CTRP' instead of creating a new one.


Using:  cuda


 33%|███▎      | 1/3 [00:00<00:00,  2.03it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:00<00:00,  2.10it/s]

[[1]
 [0]
 [0]
 ...
 [0]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:01<00:00,  2.10it/s]
[I 2025-03-20 12:40:01,008] Trial 21 finished with values: [5561.0, 0.3774490731834887, 0.29894101550665564, 0.0] and parameters: {'dropout1': 0.3, 'dropout2': 0.2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'epochs': 3, 'heads': 1, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 0.0001826731319992782, 'weight_decay': 0.007158376845470474, 'scheduler': 'Plateau', 'gnn_layer': 'GAT', 'patience_plateau': 10, 'thresh_plateau': 0.00019824982952205085, 'amsgrad': True, 'early_stop_threshold': 0.6962366285643634}. 


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:00,  2.10it/s]

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:00<00:00,  2.12it/s]

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:01<00:00,  2.13it/s]
[I 2025-03-20 12:40:03,094] Trial 22 finished with values: [5561.0, 0.4830046764349187, 0.46137787306149014, 0.46181686572566055] and parameters: {'dropout1': 0.3, 'dropout2': 0.2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'epochs': 3, 'heads': 1, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 0.0001726457241489178, 'weight_decay': 0.0020757407391285266, 'scheduler': 'Plateau', 'gnn_layer': 'GAT', 'patience_plateau': 10, 'thresh_plateau': 0.00013711763697795627, 'amsgrad': True, 'early_stop_threshold': 0.6751435029350369}. 


[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [0]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:00,  2.14it/s]

[[1]
 [0]
 [0]
 ...
 [1]
 [1]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:00<00:00,  2.14it/s]

[[1]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:01<00:00,  2.14it/s]
[I 2025-03-20 12:40:05,162] Trial 23 finished with values: [5561.0, 0.5209487094448313, 0.5456889489803319, 0.6231379233676722] and parameters: {'dropout1': 0.3, 'dropout2': 0.2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'epochs': 3, 'heads': 1, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 1.1115651645343798e-05, 'weight_decay': 0.007106074417195402, 'scheduler': 'Plateau', 'gnn_layer': 'GAT', 'patience_plateau': 10, 'thresh_plateau': 0.00010673041503551013, 'amsgrad': True, 'early_stop_threshold': 0.3127433859432738}. 


[[1]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:00,  2.34it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:00<00:00,  2.42it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:01<00:00,  2.41it/s]
[I 2025-03-20 12:40:07,090] Trial 24 finished with values: [5561.0, 0.4583274585860251, 0.45639845869587636, 0.0] and parameters: {'dropout1': 0.3, 'dropout2': 0.5, 'hidden1': 512, 'hidden2': 128, 'hidden3': 64, 'epochs': 3, 'heads': 1, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 1.0349364909468851e-05, 'weight_decay': 0.008773865692880748, 'scheduler': 'Plateau', 'gnn_layer': 'GAT', 'patience_plateau': 3, 'thresh_plateau': 0.00010909589420404582, 'amsgrad': False, 'early_stop_threshold': 0.3065483241552949}. 


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:01,  1.11it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:01<00:00,  1.11it/s]

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:02<00:00,  1.11it/s]
[I 2025-03-20 12:40:10,470] Trial 25 finished with values: [5561.0, 0.6266274510214171, 0.6171531507107211, 0.668254990341275] and parameters: {'dropout1': 0.3, 'dropout2': 0.2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'epochs': 3, 'heads': 2, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 1.0676057653687838e-05, 'weight_decay': 0.0020267680296833035, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.13471667240498725, 'step_size': 30, 'amsgrad': True, 'early_stop_threshold': 0.30032969789207553}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:01,  1.10it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:01<00:00,  1.11it/s]

[[0]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:02<00:00,  1.11it/s]
[I 2025-03-20 12:40:13,828] Trial 26 finished with values: [5561.0, 0.448954210087249, 0.43719361283809166, 0.6632186673081548] and parameters: {'dropout1': 0.1, 'dropout2': 0.2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'epochs': 3, 'heads': 2, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 1.157127912467034e-05, 'weight_decay': 0.0012976205841761402, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.10668926334303147, 'step_size': 30, 'amsgrad': True, 'early_stop_threshold': 0.3059801330056694}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:01,  1.55it/s]

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:01<00:00,  1.55it/s]

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:01<00:00,  1.53it/s]
[I 2025-03-20 12:40:16,472] Trial 27 finished with values: [5561.0, 0.6222148240816857, 0.6252022774918488, 0.39575338961371187] and parameters: {'dropout1': 0.3, 'dropout2': 0.5, 'hidden1': 512, 'hidden2': 128, 'hidden3': 64, 'epochs': 3, 'heads': 2, 'activation': 'gelu', 'optimizer': 'AdamW', 'lr': 1.982767278906544e-05, 'weight_decay': 0.00044532980305385795, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.1037592465860924, 'step_size': 30, 'amsgrad': False, 'early_stop_threshold': 0.4077843466637911}. 


[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:01,  1.32it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:01<00:00,  1.32it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:02<00:00,  1.32it/s]
[I 2025-03-20 12:40:19,393] Trial 28 finished with values: [5561.0, 0.5179065769420965, 0.5324573178849374, 0.6666666666666666] and parameters: {'dropout1': 0.3, 'dropout2': 0.5, 'hidden1': 256, 'hidden2': 128, 'hidden3': 128, 'epochs': 3, 'heads': 2, 'activation': 'gelu', 'optimizer': 'AdamW', 'lr': 2.3817094994696014e-05, 'weight_decay': 0.0005489730499479897, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.19481630939288375, 'step_size': 30, 'amsgrad': False, 'early_stop_threshold': 0.41930832283253894}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 50%|█████     | 1/2 [00:00<00:00,  1.14it/s]

[[1]
 [1]
 [0]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 2/2 [00:01<00:00,  1.14it/s]
[I 2025-03-20 12:40:21,822] Trial 29 finished with values: [5561.0, 0.5986913521541423, 0.6104016265821768, 0.6666666666666666] and parameters: {'dropout1': 0.4, 'dropout2': 0.2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'epochs': 2, 'heads': 2, 'activation': 'swish', 'optimizer': 'Adam', 'lr': 0.009090712420074238, 'weight_decay': 0.0026853575934844822, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.9453666882613563, 'step_size': 10, 'amsgrad': False, 'early_stop_threshold': 0.40260868213646256}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 2
Using:  cuda


 33%|███▎      | 1/3 [00:00<00:01,  1.55it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


 67%|██████▋   | 2/3 [00:01<00:00,  1.55it/s]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 3/3 [00:01<00:00,  1.55it/s]
[I 2025-03-20 12:40:24,478] Trial 30 finished with values: [5561.0, 0.453841858046595, 0.43073247128082415, 0.6666666666666666] and parameters: {'dropout1': 0.1, 'dropout2': 0.5, 'hidden1': 512, 'hidden2': 128, 'hidden3': 64, 'epochs': 3, 'heads': 2, 'activation': 'gelu', 'optimizer': 'AdamW', 'lr': 2.2730566217483152e-05, 'weight_decay': 5.268127903751028e-05, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.41114863732253093, 'step_size': 22, 'amsgrad': True, 'early_stop_threshold': 0.4043148395589454}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 3
Using:  cuda


 50%|█████     | 1/2 [00:01<00:01,  1.22s/it]

[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 2/2 [00:02<00:00,  1.23s/it]
[I 2025-03-20 12:40:27,662] Trial 31 finished with values: [5561.0, 0.6489553783002272, 0.6514978744674851, 0.6790494058786744] and parameters: {'dropout1': 0.3, 'dropout2': 0.1, 'hidden1': 1028, 'hidden2': 256, 'hidden3': 256, 'epochs': 2, 'heads': 2, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 6.807940918290372e-05, 'weight_decay': 0.0005189971890925012, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.40349114450015383, 'step_size': 23, 'amsgrad': True, 'early_stop_threshold': 0.3691898482839186}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 2
Using:  cuda


 50%|█████     | 1/2 [00:01<00:01,  1.21s/it]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 2/2 [00:02<00:00,  1.22s/it]
[I 2025-03-20 12:40:30,870] Trial 32 finished with values: [5561.0, 0.44163319581475263, 0.41297991015019986, 0.0] and parameters: {'dropout1': 0.3, 'dropout2': 0.1, 'hidden1': 1028, 'hidden2': 256, 'hidden3': 256, 'epochs': 2, 'heads': 2, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 0.0003863007955671243, 'weight_decay': 0.0006072016999509409, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.5010292453674664, 'step_size': 22, 'amsgrad': True, 'early_stop_threshold': 0.46274771212316224}. 


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 2
Using:  cuda


 50%|█████     | 1/2 [00:01<00:01,  1.27s/it]

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 2/2 [00:02<00:00,  1.29s/it]
[I 2025-03-20 12:40:34,234] Trial 33 finished with values: [5561.0, 0.38930233657481866, 0.3203616614681827, 0.6666666666666666] and parameters: {'dropout1': 0.3, 'dropout2': 0.1, 'hidden1': 1028, 'hidden2': 256, 'hidden3': 256, 'epochs': 2, 'heads': 2, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 7.030832709408708e-05, 'weight_decay': 4.960759013168975e-05, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.33155036137636507, 'step_size': 17, 'amsgrad': True, 'early_stop_threshold': 0.3640896539372586}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 2
Using:  cuda


 50%|█████     | 1/2 [00:01<00:01,  1.27s/it]

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 2/2 [00:02<00:00,  1.26s/it]
[I 2025-03-20 12:40:37,494] Trial 34 finished with values: [5561.0, 0.431805993738299, 0.42155987438011167, 0.6666666666666666] and parameters: {'dropout1': 0.3, 'dropout2': 0.1, 'hidden1': 1028, 'hidden2': 256, 'hidden3': 256, 'epochs': 2, 'heads': 2, 'activation': 'swish', 'optimizer': 'Adam', 'lr': 0.0001755555155287408, 'weight_decay': 1.6778504975911436e-06, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.6882791384519698, 'step_size': 25, 'amsgrad': False, 'early_stop_threshold': 0.5447833378115544}. 


[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 2


[I 2025-03-20 12:40:38,087] Trial 35 pruned. Invalid layer size configuration


Using:  cuda


 50%|█████     | 1/2 [00:01<00:01,  1.24s/it]

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1. 1. 1. ... 0. 0. 0.]


100%|██████████| 2/2 [00:02<00:00,  1.24s/it]
[I 2025-03-20 12:40:41,284] Trial 36 finished with values: [5561.0, 0.6291055050453221, 0.652082536169041, 0.0] and parameters: {'dropout1': 0.5, 'dropout2': 0.1, 'hidden1': 1028, 'hidden2': 256, 'hidden3': 256, 'epochs': 2, 'heads': 2, 'activation': 'swish', 'optimizer': 'AdamW', 'lr': 0.0007284869047590099, 'weight_decay': 0.0006512979877311376, 'scheduler': 'Cosine', 'gnn_layer': 'GATv2', 'T_max': 25, 'amsgrad': True, 'early_stop_threshold': 0.3623462520682575}. 


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[1. 1. 1. ... 0. 0. 0.]
Best model found at epoch 2
Using:  cuda


  0%|          | 0/2 [00:01<?, ?it/s]


CUDA out of memory


[I 2025-03-20 12:40:43,263] Trial 37 finished with values: [-inf, -inf, -inf, -inf] and parameters: {'dropout1': 0.5, 'dropout2': 0.1, 'hidden1': 1028, 'hidden2': 256, 'hidden3': 256, 'epochs': 2, 'heads': 3, 'activation': 'swish', 'optimizer': 'Adam', 'lr': 0.0006226321074105424, 'weight_decay': 0.003248974075912718, 'scheduler': 'Cosine', 'gnn_layer': 'Transformer', 'T_max': 20, 'amsgrad': True}. 


Using:  cuda


  0%|          | 0/2 [00:00<?, ?it/s]
[W 2025-03-20 12:40:44,716] Trial 38 failed with parameters: {'dropout1': 0.4, 'dropout2': 0.1, 'hidden1': 1028, 'hidden2': 256, 'hidden3': 256, 'epochs': 2, 'heads': 2, 'activation': 'swish', 'optimizer': 'SGD', 'lr': 0.0028260439518271088, 'weight_decay': 0.0010118534919524279, 'scheduler': 'Step', 'gnn_layer': 'GATv2', 'gamma_step': 0.8222270136420917, 'step_size': 25, 'momentum': 0.8368460374841258, 'nesterov': True} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/data/inouey2/conda/envs/genex/lib/python3.10/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_446861/672460150.py", line 78, in objective
    _, _, _, best_metrics, early_stopping_epoch = drGAT.train(
  File "/spin1/home/linux/inouey2/drGAT/drGAT/drGAT.py", line 235, in train
    train_attention = train_one_epoch(
  File "/spin1/home/linux/inouey2/drGAT/drGAT/drGA

KeyboardInterrupt: 

## Eval

In [30]:
# test_drug = test_data.values[:, 0]
# test_cell = test_data.values[:, 1]

# test_labels = np.load("data/test_labels.npy")
# test_labels = torch.tensor(test_labels).float()
# test = [drug, cell, gene, edge_index, test_drug, test_cell, test_labels]

In [63]:
# prob, res, test_attention = drGAT.eval(model, test)

['maximizemaximizemaximizemaximize']